[package]
name = "boilermates-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true } 
indexmap = { workspace = true }

[dev-dependencies]
prettyplease = { workspace = true }
insta = { workspace = true }
